name: CI

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: ["master", "main"]

  push:
    branches: ["master", "main"]

  schedule:
    - cron: "0 0 * 1 *" # Runs at the beginning of every month


concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Build the Stack
        run: docker compose -f docker-compose.yml build django

      - name: Run DB Migrations
        run: docker compose -f docker-compose.yml run --rm django python manage.py migrate

      - name: Run Django Tests
        run: docker compose -f docker-compose.yml run --rm --use-aliases django pytest

      - name: Tear down the Stack
        run: docker compose -f docker-compose.yml down

